apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-intelligent-investor-frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-intelligent-investor-frontend-prod
  template:
    metadata:
      labels:
        app: the-intelligent-investor-frontend-prod
    spec:
      containers:
        - name: the-intelligent-investor-frontend
          image: quay.io/YOUR_QUAY_USERNAME/the-intelligent-investor-frontend:prod
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: the-intelligent-investor-frontend-prod
spec:
  selector:
    app: the-intelligent-investor-frontend-prod
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: the-intelligent-investor-frontend-prod
spec:
  to:
    kind: Service
    name: the-intelligent-investor-frontend-prod
  port:
    targetPort: http
  tls:
    termination: edge